// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKLS51F2zK-qt7Uew4aaJydO8FDsw6Ym8',
    appId: '1:279500701785:web:278c76459de90396ae3148',
    messagingSenderId: '279500701785',
    projectId: 'grocery-app-9cb75',
    authDomain: 'grocery-app-9cb75.firebaseapp.com',
    storageBucket: 'grocery-app-9cb75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClbgJcM1WjFoxen8LnFZJlVdKw_AhC8XQ',
    appId: '1:279500701785:android:8279cec71e54ae25ae3148',
    messagingSenderId: '279500701785',
    projectId: 'grocery-app-9cb75',
    storageBucket: 'grocery-app-9cb75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpAiSGkHnALajyo005lOLxELOnxCFyvKQ',
    appId: '1:279500701785:ios:5b408c056c253af8ae3148',
    messagingSenderId: '279500701785',
    projectId: 'grocery-app-9cb75',
    storageBucket: 'grocery-app-9cb75.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpAiSGkHnALajyo005lOLxELOnxCFyvKQ',
    appId: '1:279500701785:ios:5b408c056c253af8ae3148',
    messagingSenderId: '279500701785',
    projectId: 'grocery-app-9cb75',
    storageBucket: 'grocery-app-9cb75.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKLS51F2zK-qt7Uew4aaJydO8FDsw6Ym8',
    appId: '1:279500701785:web:94228bda989cce94ae3148',
    messagingSenderId: '279500701785',
    projectId: 'grocery-app-9cb75',
    authDomain: 'grocery-app-9cb75.firebaseapp.com',
    storageBucket: 'grocery-app-9cb75.firebasestorage.app',
  );
}
